baseURL = 'https://hci-mtl.github.com'
defaultContentLanguage = 'en'
theme = 'hugo-theme-zen'
contentDir = 'content'

[languages]
    [languages.en]
        languageName = 'en'
        languageCode = 'en-CA'
        title = 'HCI Montreal Help Desk'
        weight = 1

[params]
    copyright = "This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)."
