baseURL = 'https://JRegimbal.github.com/HCI-Help-Desk'
defaultContentLanguage = 'en'
theme = 'ananke'
contentDir = 'content'

[languages]
    [languages.en]
        languageName = 'en'
        languageCode = 'en-CA'
        title = 'HCI Help Desk'
        weight = 1
    [languages.fr]
        languageName = 'fr'
        languageCode = 'fr-CA'
        title = "Service d'assistance HCI"
        weight = 2
        
[params]
    [params.ananke]
        show_recent_posts = false